language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mroziu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mroziu/react-test npm test

after_success:
  - docker build -t mroziu/multi-client ./client
  - docker build -t mroziu/multi-nginx ./nginx
  - docker build -t mroziu/multi-server ./server
  - docker build -t mroziu/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password_stdin
  - docker push mroziu/multi-client
  - docker push mroziu/multi-nginx
  - docker push mroziu/multi-server
  - docker push mroziu/multi-worker